# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "artii", "~> 2.1"

gem 'tty-progressbar'

gem 'csv'

gem 'colorize', '~> 0.8.1'

gem "thor"




